server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/limahotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB
      file-size-threshold: 2KB